### PR TITLE
Add details popup

### PR DESCRIPTION
**Pull request by MoRaad97**
### In this PR we

- Added popup dynamically using javascript.
- Loaded popup data dynamically using javascript.
- Added responsiveness to the popup container.
- Fixed linter errors.

### CODE REVIEW

**Review by topeogunleye — CHANGES_REQUESTED** [review]
> # Changes Required 
> ### Hi Team,
> Nice job, you are almost there.
> 
> 
> 
> ## (Highlights) Good Points: 
> * Good commit messages. :heavy_check_mark:
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * PR has a good title and summary :heavy_check_mark:
>
> ## (Changes Required) Aspects to improve: 
### I COULD NOT ADD THIS COMMENT USING GITHUB INLINE FEATURE BECAUSE YOU DIDN'T MAKE CHANGES TO THOSE LINE OF  CODE
>-  [x]  I kindly suggest that you follow the project requirements by creating your projects section dynamically with the information from the projects array.
>- [x] I kindly suggest that you do the following:
>- Create an array of object with project info where each object contains at least the following information about the project: name, description, featured image, technologies, link to live version, and link to the project source code. Ie:
```javascript
const projects = [{
    name: "Submarine game",
    description: "A Phaser3 platform game built as part of the Microverse JavaScript program.",
    image: "link_to_image.jpg",
    technologies: ["Phaser3", "JavaScript", "Jest"],
    link: "link_to_live_version.com",
}]
```
- Modal popup data is populated with the data from the projects array.

After doing the two points above, adding projects in the future will be easy
> 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> **Cheers and Happy coding! :clap::clap::clap:**
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear
> Please, remember to tag @topeogunleye in your question so I can receive the notification.
>
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by sntakirutimana72** [comment]
Forgive me, but I don't quite get what you're suggesting maybe if you could elaborate more.
The popup is loaded dynamically after the page as indicated in the project requirement.

> For reference, kindly look up a `loadWizard` function inside the `index.js` file.
> As for the popup data, kindly look up a `data` array variable inside the `static/js/static.js` file.

@topeogunleye

**Comment by topeogunleye** [comment]
> Forgive me, but I don't quite get what you're suggesting maybe if you could elaborate more. The popup is loaded dynamically after the page as indicated in the project requirement.
> 
> > For reference, kindly look up a `loadWizard` function inside the `index.js` file.
> > As for the popup data, kindly look up a `data` array variable inside the `static/js/static.js` file.
> 
> @topeogunleye

@sntakirutimana72, Thank you for making the required changes. I will check them and get back to you. I meant that you should not  add the project cards manually through HTML but instead create them in your JavaScript file and used an array of objects to store the data about your project.

**Review by topeogunleye — APPROVED** [review]
### Hi Team, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
congratulations
> 
> ## [Optional] suggestions:
> * [ ]  Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
